name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
          - os: windows-latest
            cc: cl
            cxx: cl
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      STEAMRT_SNAPSHOT: latest-steam-client-general-availability
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout steam-runtime
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/checkout@v4
      with:
        repository: ValveSoftware/steam-runtime
        path: steam-runtime
    - name: Cache steam-runtime
      if: startsWith(matrix.os, 'ubuntu')
      id: cache-steam-runtime
      uses: actions/cache@v4
      with:
        path: com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
        key: steam-runtime-${{ env.STEAMRT_SNAPSHOT }}
    - name: Download steam-runtime
      if: startsWith(matrix.os, 'ubuntu') && steps.cache-steam-runtime.outputs.cache-hit != 'true'
      run: wget --no-verbose https://repo.steampowered.com/steamrt-images-scout/snapshots/${{ env.STEAMRT_SNAPSHOT }}/com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
    - name: Install steam runtime
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update
        ./steam-runtime/setup_chroot.sh --i386 --tarball ./com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
        sudo < /etc/schroot/chroot.d/steamrt_scout_i386.conf sed -i 's/groups=sudo/groups=adm/g' /etc/schroot/chroot.d/steamrt_scout_i386.conf

    - name: Build on Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        schroot --chroot steamrt_scout_i386 -- cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPOLLY=ON -B build -S . -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-undefined" -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        schroot --chroot steamrt_scout_i386 -- cmake --build build --target all
        schroot --chroot steamrt_scout_i386 -- cmake --build build --target install
    - name: Build on Linux with vgui
      if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.cc, 'gcc')
      run: |
        schroot --chroot steamrt_scout_i386 -- cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPOLLY=ON -B build-vgui -S . -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-undefined" -DUSE_VGUI=ON -DCMAKE_INSTALL_PREFIX="$PWD/dist-vgui"
        cp vgui_support/vgui-dev/lib/vgui.so build-vgui/cl_dll
        cp vgui_support/vgui-dev/lib/vgui.so build-vgui
        schroot --chroot steamrt_scout_i386 -- cmake --build build-vgui --target all
        schroot --chroot steamrt_scout_i386 -- cmake --build build-vgui --target install

    - name: Set developer command prompt for Windows x86
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build on Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_INSTALL_PREFIX="dist"
        cmake --build build --target all
        cmake --build build --target install
    - name: Build on Windows with vgui
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DUSE_VGUI=ON -DCMAKE_INSTALL_PREFIX="dist-vgui"
        cmake --build build --target all
        cmake --build build --target install

    - name: Set developer command prompt for Windows x86_64
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build on Windows x64
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build64 -S . -DCMAKE_INSTALL_PREFIX="dist64" -D64BIT=ON
        cmake --build build64 --target all
        cmake --build build64 --target install

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Extract gamedir
      shell: bash
      run: echo "gamedir=$(grep build/CMakeCache.txt -Ee 'GAMEDIR:STRING=[a-z]+' | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
      id: extract_gamedir
    - name: Upload linux artifact
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload linux artifact with vgui
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows artifact
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows x64 artifact
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows_x64
        path: dist64/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows artifact with vgui
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Build Android APK
        env:
          KEYSTORE_FILE_PATH: ${{ github.workspace }}/signingkey.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ env.KEYSTORE_FILE_PATH }}
          ./gradlew assembleRelease
          find app/build/outputs/apk/release/ -name "*.apk" -exec cp {} ../app-release.apk \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hlsdk-${{ github.ref_name }}-android
          path: app-release.apk

  macos:
    name: macOS
    strategy:
      matrix:
        include:
          - os: macos-15
            arch: x86_64
          - os: macos-latest
            arch: arm64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: brew install cmake ninja fontconfig

      - name: Configure
        run: |
          cmake -G Ninja \
            -B build \
            -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DPOLLY=ON \
            -DCMAKE_INSTALL_PREFIX="$PWD/dist"

      - name: Build
        run: |
          cmake --build build --target all
          cmake --build build --target install

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract gamedir
        shell: bash
        run: echo "gamedir=$(grep build/CMakeCache.txt -Ee 'GAMEDIR:STRING=[a-z]+' | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
        id: extract_gamedir

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hlsdk-${{ steps.extract_branch.outputs.branch }}-macos-${{ matrix.arch }}
          path: dist/${{ steps.extract_gamedir.outputs.gamedir }}


  release:
    name: Release
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/insecure') && always()
    needs: [ build, android, macos ]
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Prepare Release Files
        run: |
          mkdir -p release-dist
          find all-artifacts -name "app-release.apk" -exec cp {} release-dist/hlsdk-${{ github.ref_name }}-android.apk \;
          cd all-artifacts
          for d in */; do
            dir_name=$(basename "$d")
            if [[ "$dir_name" != *"android"* ]]; then
              zip -r "../release-dist/${dir_name}.zip" "$dir_name"
            fi
          done
          
      - name: Remove old release
        run: |
          TAG_NAME=${{ github.ref_name == 'main' && 'continuous' || format('continuous-{0}', github.ref_name) }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          if gh release view "$TAG_NAME" --repo ${{ github.repository }} > /dev/null 2>&1; then
            gh release delete "$TAG_NAME" --yes --cleanup-tag --repo ${{ github.repository }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload new release
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --title "${{ github.ref_name }} development build" \
            --prerelease \
            release-dist/* \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE_ID: "1496163272204750939"
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          curl -X PATCH -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "Insecure latest development build",
                "url": "https://github.com/yalnawg/insecure/releases/tag/${{ env.TAG_NAME }}",
                "description": "* [Android](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-android.apk)\n* [Linux with VGUI](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-linux-vgui.zip)\n* [Linux](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-linux.zip)\n* [Windows (i386)](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-windows.zip)\n* [Windows (x64)](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-windows_x64.zip)\n* [macOS (arm64)](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-macos-arm64.zip)\n* [macOS (x86_64)](https://github.com/yalnawg/insecure/releases/download/${{ env.TAG_NAME }}/hlsdk-${{ github.ref_name }}-macos-x86_64.zip)",
                "color": 5258682,
                "timestamp": "'"$TIMESTAMP"'",
                "thumbnail": {
                  "url": "https://cdn.discordapp.com/attachments/1444986673309155339/1496877213067251802/2034866.png?ex=69eb7b0a&is=69ea298a&hm=cfc3b1f3d3fb77fcae19e0916604157ad75c305a89a39debd72e85dbc3661da6&"
                },
                "footer": {
                  "text": "commit '"$SHORT_SHA"'"
                }
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "Source Code",
                    "url": "https://github.com/Elinsrc/hlsdk-portable/tree/insecure"
                  }
                ]
              }
            ]
          }' "${DISCORD_WEBHOOK}/messages/${MESSAGE_ID}"

